### ISSUE TITLE
输入框的位置的建议

### ISSUE THREAD

**Issue by shanyang121** [Quorafind/Obsidian-Thino#221]
![image](https://user-images.githubusercontent.com/80085868/169627596-9e0d2769-8c4d-4417-8b96-85cb62100ef5.png)
目前输入框的位置默认是在上面的，这样输入可能比较方便
但是一般的电脑屏幕都是横向的，所以上下方向的空间比较小。而查看笔记时，上方的输入框占据了大量的时间，导致实际一次只能岔查看两三条，而且输入框在上面，还要用眼去找输入框和笔记的分界，才能开始读笔记，没有直接笔记在最上面方便。
建议电脑端也和手机端一样，提供输入框在下面和浏览时隐藏的选项，希望作者考虑。

**Comment by cumany** [comment]
这个用css 片段就解决了
```css
div[data-type='memos_view']:not(.mobile-view) #page-wrapper  .memo-editor-wrapper {
  bottom: 0;
  position: fixed;
  width: 70%;
}

  div[data-type='memos_view']:not(.mobile-view) #page-wrapper > .content-wrapper {
  height: 75%;
}

div[data-type='memos_view']:not(.mobile-view)  .common-editor-wrapper > .common-tools-wrapper > .btns-container {
  position: absolute;
  left: 70%;
}

```
