### ISSUE TITLE
Feature Request: 交互细节一点点小建议

### ISSUE THREAD

**Issue by xhuajin** [Quorafind/Obsidian-Thino#457]
### Feature Requested | 请求的功能

1. **对于某个 thino 块，『置顶』按钮和『more action』按钮会有遮挡**：鼠标 hover 『more action』的时候，再移动到『置顶』按钮经常无法点击到『置顶』按钮，只需要给『置顶』按钮加一个 z-index 就可以解决了。

2. 左上角如果是日历的时候，鼠标 hover userinfo-header 的时候会突然出现 “thino 标签 天” 这三个内容，整体内容突然下降有点突兀。我试着给 userinfo-header-container 在 hover 的时候加一个高度的变化，让这个过程有个过渡

```css
div[data-type="thino_view"]:has(.heatmap-date-picker-wrapper) .user-banner-container {
  height: 52px;
  transition: all 0.2s ease-in;
}

div[data-type="thino_view"]:has(.heatmap-date-picker-wrapper) .user-banner-container:hover {
  height: 140px;
}
```

由于 hover 的地方是 title 但是是让子元素 display: flex 且两者不重合，因此父元素添加的 hover 时样式的修改无法加到子元素上，因此下方的 userinfo 出现的时候会有一瞬间与下方日历重合，动画只有 0.2s 所以尚能接受。

3. 使用『动态』视图的时候，上方切换视图那一行 section-header-container 会被隐藏，导致必须要在有输入框的时候才能切换视图，我试着改成了平常高度减少且透明、hover的时候高度恢复且不透明，这样就可以**把切换视图与是否编辑解耦**。

```css
div[data-type="thino_view"]
  .content-wrapper:has(.moments-view:not(.show-editor))
  .section-header-container {
  display: inherit;
}

div[data-type="thino_view"]
  .memos-moments-view
  .section-header-container.memos-header-container {
  opacity: 0;
  height: 8px;
  transition: 0.2s all ease-in 0.1s;
}

div[data-type="thino_view"]
  .memos-moments-view
  .section-header-container.memos-header-container:hover {
  height: 40px;
  opacity: 1;
}
```

4. 使用『动态』视图的时候，新建 thino 块时点击相机图标，然后就会在上方出现一个输入框，整体内容会突然下移。是否可以把他改为悬浮编辑器，我试着用 css 实现了一下，但是只用 css 只能有个入场动画，没有离场动画

```css
div[data-type="thino_view"]:has(.moments-view.show-editor)
  .memos-sidebar-wrapper,
div[data-type="thino_view"]
  .content-wrapper:has(.moments-view.show-editor)
  .memolist-wrapper {
  opacity: 0.3;
  animation-name: hide;
  animation-duration: 0.2s;
}

div[data-type="thino_view"]:has(.moments-view.show-editor)
  .memos-sidebar-wrapper,
div[data-type="thino_view"]
  .content-wrapper:has(.moments-view.show-editor)
  .memolist-wrapper
  .thino-moment-wrapper {
  pointer-events: none;
}

div[data-type="thino_view"]:has(.moments-view.show-editor)
  .memos-moments-view
  .memo-editor-wrapper {
  position: absolute;
  z-index: 1;
  top: calc(30%);
  left: calc(0% - var(--memos-sidebar-width) / 2);
  /* width: -webkit-fill-available; */
  box-shadow: rgba(0, 0, 0, 0.5) 0px 16px 70px;
  transform: scale(1) translate3d(0px, 0px, 0px);
  animation-name: show;
  animation-duration: 0.2s;
  animation-timing-function: ease;
}

div.workspace-leaf-content.mobile-view[data-type="thino_view"]:has(
    .moments-view.show-editor
  )
  .memos-moments-view
  .memo-editor-wrapper {
  width: auto;
  left: 10%;
  right: 10%;
}

@keyframes show {
  0% {
    opacity: 0.3;
  }
  100% {
    opacity: 1;
  }
}

@keyframes hide {
  0% {
    opacity: 1;
  }
}
```

### 建议一

![image](https://github.com/Quorafind/Obsidian-Thino/assets/114134574/ced1890c-c848-4e58-a336-108ff38ac11f)

### 建议二

修改前：
![recording](https://github.com/Quorafind/Obsidian-Thino/assets/114134574/570e99ff-41cc-4ddc-bb7c-e647dd009546)

修改后：
![recording](https://github.com/Quorafind/Obsidian-Thino/assets/114134574/b2904bb4-9676-4bb8-89e1-8647e2e0608b)

### 建议三

修改前：
![recording](https://github.com/Quorafind/Obsidian-Thino/assets/114134574/233d6ae0-65d5-482d-97ba-e3c9d1482a74)

修改后：
![recording](https://github.com/Quorafind/Obsidian-Thino/assets/114134574/d1d22b13-992a-4597-a783-b7a8d23da749)

### 建议四

修改前：
![recording](https://github.com/Quorafind/Obsidian-Thino/assets/114134574/e0121659-9272-4cd6-90ec-dc58c351f201)

修改后：

https://github.com/Quorafind/Obsidian-Thino/assets/114134574/ddee334c-a814-49c2-ac2f-f7ee7010dc4c

### Checklist | 检查清单

- [X] The feature would be useful to more users than just me. 该功能对于不仅仅是我自己的用户来说是有用的。
