### ISSUE TITLE
Feature Request: 动态视图背景图能否增加固定选项

### ISSUE THREAD

**Issue by xiaoxiang01a** [Quorafind/Obsidian-Thino#508]
### Feature Requested | 请求的功能

动态视图背景当鼠标悬浮的时候才会下移，然后缓慢的露出搜索框，有时需要经常搜索和筛选，能否增加固定的选项

### Checklist | 检查清单

- [X] The feature would be useful to more users than just me. 该功能对于不仅仅是我自己的用户来说是有用的。

**Comment by Quorafind** [comment]
自行使用 css snippet 就行，在你的库的 `.obsidian/snippets` 文件夹中创建任意，例如 `thino.css`，将以下内容填入：

```css
div[data-type="thino_view"]:not(.mobile-view) .memos-moments-view .section-header-container.memos-header-container {
    height: 40px;
    opacity: 1;
}
```
