### ISSUE TITLE
Feature Request: 左侧日历图模式下，顶部的“Thino/标签/天”模块固定

### ISSUE THREAD

**Issue by RogerProSelf** [Quorafind/Obsidian-Thino#568]
### Feature Requested | 请求的功能

当前左边侧栏在日历图模式下，“Thino/标签/天”总是默认隐藏的，只有鼠标到顶部那块区域才显示，能否设置固定显示，一方面是方便查看，另一方面是通过日历组件点选日期的时候，如果鼠标不小心划到上部，日历组件就会下移，造成点选的不方便。谢谢！

### Checklist | 检查清单

- [X] The feature would be useful to more users than just me. 该功能对于不仅仅是我自己的用户来说是有用的。

**Comment by Quorafind** [comment]
你可以加一个 css snippet 来实现该功能：

```css
div[data-type="thino_view"]:not(:has(.daily-thinos-view-wrapper)):has(.memos-sidebar-wrapper .heatmap-date-picker-wrapper) .user-banner-container .status-text-container {
   display: flex;
}

div[data-type="thino_view"]:has(.heatmap-date-picker-wrapper) .user-banner-container {
    height: 140px;
}
```
