### ISSUE TITLE
[FR]: Hope the icon at the top of the input box can be hidden

### ISSUE THREAD

**Issue by i-iooi-i** [Quorafind/Obsidian-Thino#610]
### Feature Requested | 请求的功能

顶部这几项功能是否可以考虑像 “动态” 模式下自动隐藏，或者设置里增加一个不显示的功能呢？

- 第一次使用Thino就被这个鼠标滑过，就闪来闪去的搜索框搞得很影响心情了。
- 非高频使用的功能项。
- 去掉这排图标，页面更加干净清爽，无视觉干扰，输入体验更佳。

### Relevant Screenshot | 相关截图

https://github.com/Quorafind/Obsidian-Thino/assets/1827701/99218453-e89f-453a-8a9b-9caf91975ac2

### Checklist | 检查清单

- [X] The feature would be useful to more users than just me. 该功能对于不仅仅是我自己的用户来说是有用的。

**Comment by i-iooi-i** [comment]
![image](https://github.com/Quorafind/Obsidian-Thino/assets/1827701/2788d326-74ea-4270-8fce-ea0ad7ea2709)

而且隐藏顶部菜单栏的话，放在右侧栏看上去也会更加简洁美观，大大提升随手记录灵感的舒适度。

**Comment by Quorafind** [comment]
可以增加以下的css样式强制其不展示

```css
.section-header-container.memos-header-container * {
    display: none !important;
}
```
